# Linear queue for the main branch.
queue_rules:
  - name: high_priority_main
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body | trim }}
    queue_conditions:
      - base=master
      - label=priority:high
      - or:
          - check-pending=integration-test-result
          - check-success=integration-test-result
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
      # Rebase PRs with fixup commits are allowed to enter the merge queue but 
      # should not be allowed to merge if there are leftover fixup commits after rebase
      - or:
          - label=bypass:linear-history
          - check-success=no-fixup-commits
          - check-skipped=no-fixup-commits
      # Require integration tests before merging only
      - or:
          - label=bypass:integration
          - check-success=integration-test-result
  - name: main
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body | trim }}
    queue_conditions:
      - base=master
      - or:
          - check-pending=integration-test-result
          - check-success=integration-test-result
          - label=bypass:integration
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
      # Rebase PRs with fixup commits are allowed to enter the merge queue but 
      # should not be allowed to merge if there are leftover fixup commits after rebase
      - or:
          - label=bypass:linear-history
          - check-success=no-fixup-commits
          - check-skipped=no-fixup-commits
      # Require integration tests before merging only
      - or:
          - label=bypass:integration
          - check-success=integration-test-result

pull_request_rules:
  - name: merge to master
    conditions:
      - base=master
      - label=automerge:no-update
      - or:
          - '#commits-behind=0'
          - label=bypass:linear-history
    actions:
      queue:
        merge_method: merge
  - name: rebase updates then merge to master
    conditions:
      - base=master
      - label=automerge:rebase
      - or:
          - '#commits-behind>0'
          - linear-history
    actions:
      queue:
        merge_method: merge
        update_method: rebase
  - name: squash to master
    conditions:
      - base=master
      - label=automerge:squash
    actions:
      queue:
        merge_method: squash
  - name: rebase and autosquash
    conditions:
      - base=master
      - label=automerge:rebase
      - '#commits-behind=0'
      - or:
        - -linear-history
        - check-failure=no-fixup-commits
      - -draft
    actions:
      rebase:
        autosquash: true
